from enum import StrEnum

__all__ = [
    "ErrorCodes",
]


class ErrorCodes(StrEnum):
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    CLIENT_INITIALIZATION_ERROR = "CLIENT_INITIALIZATION_ERROR"
    HTTP_ERROR = "HTTP_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
