name: Secret Leaks

on:
  push:
    branches:
      - "**"
  pull_request:
  schedule:
    - cron: "17 4 * * 1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: secret-leaks-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  trufflehog:
    name: Scan for secrets
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@27b0417c16317ca9a472a9a8092acce143b49c55 # v3.95.9
        with:
          version: "3.95.9"
          extra_args: --results=verified,unknown
